#!/usr/bin/env node
/**
 * sync-version.js — regenerates src/version.js from package.json (N12).
 * Wired into prestart/prebuild so the in-app version can never drift again.
 */
const fs = require('fs');
const path = require('path');
const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));
const out = `// AUTO-GENERATED by scripts/sync-version.js — do not edit by hand.
export const APP_VERSION = ${JSON.stringify(pkg.version)};
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'version.js'), out);
console.log(`[sync-version] src/version.js ← ${pkg.version}`);
