#!/usr/bin/env node
/**
 * sync-version.js — regenerates src/version.js from package.json (N12).
 * Wired into prestart/prebuild so the in-app version + About metadata can never
 * drift from the real build again.
 */
const fs = require('fs');
const path = require('path');
const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));

const name = (pkg.build && pkg.build.productName) || pkg.name || 'AuthNo';
const author = (pkg.author && pkg.author.name) || pkg.author || 'Unknown';
const email = (pkg.author && pkg.author.email) || '';
const repoRaw = (pkg.repository && (pkg.repository.url || pkg.repository)) || '';
const repository = String(repoRaw).replace(/^git\+/, '').replace(/\.git$/, '');
const buildDate = new Date().toISOString().slice(0, 10);

const out = `// AUTO-GENERATED by scripts/sync-version.js — do not edit by hand.
export const APP_VERSION = ${JSON.stringify(pkg.version)};
export const APP_NAME = ${JSON.stringify(name)};
export const APP_AUTHOR = ${JSON.stringify(author)};
export const APP_SUPPORT_EMAIL = ${JSON.stringify(email)};
export const APP_REPOSITORY = ${JSON.stringify(repository)};
export const APP_BUILD_DATE = ${JSON.stringify(buildDate)};
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'version.js'), out);
console.log(`[sync-version] src/version.js ← ${name} v${pkg.version} (${buildDate})`);
